project:
  type: website
  output-dir: docs

website:
  title: "Deep Learning by HRM"
  search: false
  navbar:
    style: "floating"
    pinned: false
    tools:
      - icon: youtube
        href: https://www.youtube.com/playlist?list=PLn_Nuy1c1Oj9qibyyC4iEitbJ_uY-iAm6
        target: _blank
      - icon: house
        href: https://hrmiitm.github.io

  sidebar:
    style: "floating"
    search: false
    collapse-level: 1
    contents:
      - text: "About The Course"
        href: about_dl.qmd
      - section: "Week1"
        href: index.qmd
        contents:
          - mcculloch_pits.qmd
          - classical_perceptron.qmd
          - classical_perceptron_training.qmd
      - section: "Week2"
        href: Week/Week2/week2.qmd
        contents:
          - Week/Week2/boolean.qmd
          - Week/Week2/represent_boolean.qmd
          - Week/Week2/sigmoid.qmd
          - Week/Week2/taylor_gd.qmd
          - Week/Week2/gd.qmd
      - text: "Assignment 1 and 2"
        href: Week/assignment1_2.qmd
      

format:
  html:
    icon: true
    theme: 
      light: litera
      dark: sketchy
    css: styles.css
    toc: true



